# Generated by Django 4.1.6 on 2023-03-27 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0005_alter_profile_fav_org"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="fav_fighters",
        ),
        migrations.AddField(
            model_name="profile",
            name="fav_fighter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="firstApp.fighter",
            ),
        ),
    ]
