# Generated by Django 4.1.6 on 2023-03-27 15:55

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0006_remove_profile_fav_fighters_profile_fav_fighter"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_update",
            field=models.DateTimeField(
                auto_now=True, verbose_name=django.contrib.auth.models.User
            ),
        ),
    ]
