# Generated by Django 4.2 on 2023-04-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0008_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="body",
            field=models.CharField(max_length=900),
        ),
    ]
