# Generated by Django 4.2 on 2023-04-06 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0010_categroty_event_fight"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("kg", models.IntegerField()),
                ("lbs", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="fight",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="firstApp.category"
            ),
        ),
        migrations.DeleteModel(
            name="Categroty",
        ),
    ]
