# Generated by Django 4.2 on 2023-04-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0011_category_alter_fight_category_delete_categroty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="kg",
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
