# Generated by Django 4.2 on 2023-06-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0014_prediction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="description",
            field=models.CharField(max_length=2500),
        ),
    ]
