# Generated by Django 4.2 on 2023-06-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0015_alter_organization_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="fight",
            name="main_event",
            field=models.BooleanField(default=False),
        ),
    ]
