# Generated by Django 4.2 on 2023-06-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0016_fight_main_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="fight",
            name="co_main",
            field=models.BooleanField(default=False),
        ),
    ]
