# Generated by Django 4.2 on 2023-07-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0018_profile_profile_image_delete_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
