# Generated by Django 4.2 on 2023-07-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0019_alter_profile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="fighter",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="firstApp.category",
            ),
        ),
    ]
