# Generated by Django 4.2 on 2023-07-07 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0020_fighter_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="fighter",
            name="orga",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="firstApp.organization",
            ),
        ),
    ]
