# Generated by Django 4.1.6 on 2023-03-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="fighter",
            name="loss",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fighter",
            name="win",
            field=models.IntegerField(default=0),
        ),
    ]
